# Generated by Django 3.1 on 2020-08-12 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userlog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
